### ISSUE TITLE
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by ErikUden** [Red5d/docker-autocompose#29] opened 2021-10-25 09:20 UTC
Is there a linux/arm/v8 version yet? If not, no problem! I can manually copy the stacks ^^
Just wondering if I am doing something wrong!

**Comment by maxcanna** [comment] 2021-11-30 22:11
Duplicate of #27

**Closed as completed** 2022-04-09 04:19 UTC
